POST http://localhost:3333/api/links
Content-Type: application/json

{
  "code": "itgest",
  "url": "https://itgest.ao"
}

###

GET http://localhost:3333/api/links
Content-Type: application/json


###
GET http://localhost:3333/api/metrics
Content-Type: application/json


###

GET http://localhost:3333/itgest
Content-Type: application/json